In [14]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

from scipy.spatial.distance import pdist, squareform
from scipy.cluster.hierarchy import single, cophenet

from gower_metric import Gower

In [15]:
n_rows = 100
df = pd.read_csv('../../comparison/data/adult.csv').head(n_rows)

df = df[['age', 'educational-num', 'race', 'gender', 'hours-per-week', 'relationship', 'occupation', 'education', 'workclass']]
df.replace(to_replace='?', value=np.nan, inplace=True)

In [16]:
print(df.head())

   age  educational-num   race  gender  hours-per-week relationship  \
0   25                7  Black    Male              40    Own-child   
1   38                9  White    Male              50      Husband   
2   28               12  White    Male              40      Husband   
3   44               10  Black    Male              40      Husband   
4   18               10  White  Female              30    Own-child   

          occupation     education  workclass  
0  Machine-op-inspct          11th    Private  
1    Farming-fishing       HS-grad    Private  
2    Protective-serv    Assoc-acdm  Local-gov  
3  Machine-op-inspct  Some-college    Private  
4                NaN  Some-college        NaN  


In [17]:
feature_types = {
    "age": "ratio_scale_interval",
    "educational-num": "ratio_scale_interval",
    "race": "categorical_nominal",
    "gender": "categorical_nominal",
    "hours-per-week": "ratio_scale_interval",
    "relationship": "categorical_nominal",
    "occupation": "categorical_nominal",
    "education": "categorical_nominal",
    "workclass": "categorical_nominal"
}

In [18]:
gower = Gower(feature_types=feature_types).fit(df)
df = df.to_numpy()

In [19]:
Z = single(pdist(df, metric=gower))
c, _ = cophenet(Z, pdist(df, metric=gower))

In [20]:
print(f"Cophenetic correlation coefficient: {c:.4f}")

Cophenetic correlation coefficient: 0.5804


In [21]:
print(f"{squareform(cophenet(Z))}")

[[0.         0.26187516 0.26187516 ... 0.26187516 0.26187516 0.26187516]
 [0.26187516 0.         0.24693085 ... 0.16301476 0.06564626 0.18361638]
 [0.26187516 0.24693085 0.         ... 0.24693085 0.24693085 0.24693085]
 ...
 [0.26187516 0.16301476 0.24693085 ... 0.         0.16301476 0.18361638]
 [0.26187516 0.06564626 0.24693085 ... 0.16301476 0.         0.18361638]
 [0.26187516 0.18361638 0.24693085 ... 0.18361638 0.18361638 0.        ]]
