In [26]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

from sklearn.metrics import pairwise_distances

from gower_metric import Gower


There is also possibility to use scikit-learn pairwaise distances with our API. Because one will also operate on string and boolean values, we have to pass custom function as well.

In [27]:
n_rows = 100
df = pd.read_csv('../../comparison/data/adult.csv').head(n_rows)

df = df[['age', 'educational-num', 'race', 'gender', 'hours-per-week', 'relationship', 'occupation', 'education', 'workclass']]

In [28]:
# process data -> where spot '?' replace with NaN
df.replace(to_replace='?', value=np.nan, inplace=True)

In [29]:
print(df.head())

   age  educational-num   race  gender  hours-per-week relationship  \
0   25                7  Black    Male              40    Own-child   
1   38                9  White    Male              50      Husband   
2   28               12  White    Male              40      Husband   
3   44               10  Black    Male              40      Husband   
4   18               10  White  Female              30    Own-child   

          occupation     education  workclass  
0  Machine-op-inspct          11th    Private  
1    Farming-fishing       HS-grad    Private  
2    Protective-serv    Assoc-acdm  Local-gov  
3  Machine-op-inspct  Some-college    Private  
4                NaN  Some-college        NaN  


In [30]:
feature_types = {
    "age": "ratio_scale_interval",
    "educational-num": "ratio_scale_interval",
    "race": "categorical_nominal",
    "gender": "categorical_nominal",
    "hours-per-week": "ratio_scale_interval",
    "relationship": "categorical_nominal",
    "occupation": "categorical_nominal",
    "education": "categorical_nominal",
    "workclass": "categorical_nominal"
}

In [ ]:
gower = Gower(feature_types=feature_types).fit(df)

In [32]:
matrix = pairwise_distances(df, metric=gower, n_jobs=-1, ensure_all_finite=False)

In [33]:
print("Gowers distance matrix: \n", matrix)

Gowers distance matrix: 
 [[0.         0.5010286  0.6043512  ... 0.5014763  0.53022533 0.58275058]
 [0.5010286  0.         0.39240389 ... 0.17220187 0.16676287 0.38292448]
 [0.6043512  0.39240389 0.         ... 0.42703963 0.42160062 0.5973582 ]
 ...
 [0.5014763  0.17220187 0.42703963 ... 0.         0.26806527 0.52867133]
 [0.53022533 0.16676287 0.42160062 ... 0.26806527 0.         0.41212121]
 [0.58275058 0.38292448 0.5973582  ... 0.52867133 0.41212121 0.        ]]
